### ISSUE TITLE
M02: UAT

### ISSUE THREAD

**Issue by michelleif** [LD4P/sinopia_profile_editor#183]
User acceptance tests for Milestone 2: Profile “Dress Rehearsal” + “Simple Search of Casalini data
#### Profile Dress Rehearsal
- [x] Load profile into Editor to see the form
- [x] Enter data into literal field
- [ ] See default values and be able to change them
--**not fully tested due to LD4P/sinopia_editor/#390**
-- _NOTE: we don't support (nor does LC as far as we can tell) defaults for "true" lookups; we do support default for "pick from this list" sort of lookups_
- [x] Search for and select values in authoritative sources as specified in Profile (tested with GeoNames water source and LOC all subjects)
- [x] Add multiple values to fields where allowed (pass for literal and lookup, n/a for resource)
- [x] UX improvements re repeatable literal and lookup fields LD4P/sinopia_editor#347 for UX improvements
- [x] Be prevented from adding multiple values where not allowed (done for literal and lookup; for Resource, see LD4P/sinopia_editor#346)
- [x] For properties where object is another "form", see a button to open that "form" *NOTE: to test this you have to manually edit Profile JSON to refer to a "form" ID that is known by the Editor spoof: one that will work is "resourceTemplate:bf2:Note"*
- [x] for property type Resource, get visual confirmation that you indeed entered something in the modal form (NOTE: this doesn't work properly yet for type=Resource and repeatable=true, see LD4P/sinopia_editor#346)
- [x] See help text as hyperlink or tooltip per Profile
- [x] Use tab key to advance through fields, not just mouse
- [x] Enter diacritics and non-Roman script (tested using Mac language keyboards)
- [x] indicate language of entered literal

NOTES ON THINGS TO EXPECT LATER:
- Search more than one QA source at a time if specified in Profile.
LD4P/sinopia_editor#348 (as of 4/3 this works on DEV)
- when property type=Resource, *repeatable = true*, be able to open the form multiple times, adding data each time, seeing visual confirmation of each repetition, and and get visual indication when Resource is _not_ repeatable  LD4P/sinopia_editor#346
- Linked Data Editor warning if required fields are empty does not come until M4
- Preview RDF button exists but is not fully operational until M4
- assuming default with propertyType=Resource doesn't make sense so are ignoring that if specified in ProfileEditor

#### Casalini data, *postpone to milestone 3*
- [x] Specify Casalini as option for lookup in Profile Editor
- [x] in Editor, search for and select entities/values from Casalini data, as specified in profile

**Comment by ndushay** [comment]
@michelleif is this ... done done?  if so, wanna close it?

**Comment by michelleif** [comment]
@ndushay leaving this open until the default issues are fixed
